<?php

########################################################################
# Extension Manager/Repository config file for ext: "projectseavieuw"
#
# Auto generated by Extension Builder 2012-12-15
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'project_seavieuw',
	'description' => 'Display photo and video stills from a projects',
	'category' => 'plugin',
	'author' => 'Ben van Kruistum',
	'author_email' => 'ben@u-creations.nl',
	'author_company' => 'u-creations',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => 'uploads/tx_projects_seavieuw',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'extbase' => '1.3',
			'fluid' => '1.3',
			'typo3' => '4.5',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>